Feat persist
duo-rs/duo pull request #4
Opened 2022-08-27 00:19 UTC by Taylor-lagrange

[design documentation](https://yo93p0jbnb.feishu.cn/docx/doxcnRTiahtmEB3R4YAPe1A2kxc)

2022-08-28 08:07 UTC, Folyd commented
Thanks for working on this. Did you run `cargo clippy` and `cargo fmt`?

2022-08-28 11:20 UTC, Taylor-lagrange commented
> Thanks for working on this. Did you run `cargo clippy` and `cargo fmt`?

yes

2022-08-28 12:24 UTC, Folyd requested changes
Looks good overall. However, `clone()` is a litter bit too much, it's be better if the code more Rust idiomatic, such as iterating and error handling.

2022-08-28 16:16 UTC, Taylor-lagrange commented on duo/src/data/persist.rs
> +                            for log in data.logs {
If you use iterators, you need to use async closures, you need to capture trace_writer&log_writer, the ownership problem is difficult to solve.

2022-08-28 16:19 UTC, Taylor-lagrange commented on duo/src/data/persist.rs
> +                            for log in data.logs {
Other for loops have been modified（those for loops that don't have ownership issues）

2022-08-28 16:21 UTC, Taylor-lagrange commented on duo/src/data/reader.rs
> +    pub fn get_len(len: &[u8]) -> usize {
function name has been modified and annotated for more unify semantics

2022-08-28 16:22 UTC, Taylor-lagrange commented
> Thanks for working on this. Did you run `cargo clippy` and `cargo fmt`?

done

2022-09-25 15:38 UTC, Folyd commented
Looks good. Thanks for working on this. @Taylor-lagrange

2022-09-25 15:38 UTC, merged